In [74]:
import numpy as np #Creating a function that generates matrix with geometric progress for each row
def Vandermonde (list_a,boolean):
    temp=[]
    M=len(list_a)
    N=M-1
    if (boolean==True):
            temp=[list_a[i]**j for i in range(0,M) for j in range(0,N)]
    else:
            temp=[list_a[i]**(N-j-1) for i in range(0,M) for j in range(0,N)]
    return np.array(temp).reshape(M,N)
    

In [75]:
list_a=[1,2,3,4]

In [76]:
print(Vandermonde (list_a,True))# Passing the list with increasing as True

[[ 1  1  1]
 [ 1  2  4]
 [ 1  3  9]
 [ 1  4 16]]


In [77]:
list_a=[1,2,3,4]

In [78]:
print(Vandermonde (list_a,False))# Passing the list with increasing as False

[[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]]
